### ISSUE TITLE
Describe the difference between `demand`-backed reverse auctions, and two-way auction reverse phase

### ISSUE THREAD

**Issue by nmushegian** [rainbeam/token-auction#1]
In the two-way auction, the token is available in the auction and does not require a trustworthy `demand` function - only a trustworthy ERC20 implementation.

**Comment by rainbeam** [comment]
Here's what I'm currently thinking:

1. Reverse auctions are just a limit of the two way auction (that's how I'm implementing them anyway), with a configurable upper starting limit.

2. A `demand` backed auction will use this reverse auction, but pass in a custom ERC20 token that wraps the `demand` logic in `token.transfer`.

This way we keep the basic auctions agnostic about what is using them, with the shim to Maker being the custom token. The call to `demand` will only be realised when the bidder claims.

Working on the details of the reverse auction today. Will get to the token wrapper after.

**Comment by nmushegian** [comment]
1) sounds right but 2) sounds wrong... right now we have a `TokenSupplyManager` which is NOT the same address as the ERC20 it provides. There's no way to update the fixed ERC20 frontends of our dappsys-based tokens - other functions are on other entrypoints. At the very least, define a new `DemandableERC20` and define the function on it. I'd still prefer separate token and supply provider addresses

**Comment by rainbeam** [comment]
After further discussion the plan is to implement the demandable reverse auction separate to the main auctions.

The `DemandableERC20` token lookalike that would wrap the `demand` logic is probably too hacky and could lead to confusion in future.

**Comment by rainbeam** [comment]
implemented in rainbeam/demanding-auction
