### ISSUE TITLE
continuously send available bids to seller?

### ISSUE THREAD

**Issue by rainbeam** [rainbeam/token-auction#11]
Currently the seller has to claim if they want to get their auction winnings. There is another approach, which is to send them the winnings as soon as they become available (i.e. the excess bid each time it is made).

**Comment by rainbeam** [comment]
Doing this would remove the need for two different claim functions, as in #7

**Comment by nmushegian** [comment]
👍

**Comment by rainbeam** [comment]
Implemented as of 4207ee0
