### ISSUE TITLE
Allow distinct auction creator / beneficiary.

### ISSUE THREAD

**Issue by rainbeam** [rainbeam/token-auction#12]
Definitions:

1. `creator` creates an auction on behalf of the `beneficiary`

2. the `beneficiary` receives all of the auction buy token proceeds

3. the `creator` can be the same as the `beneficiary`

Question:

1. On auction creation, the auction takes the sell token into escrow. Should it be taken from the `creator`, the `beneficiary` or somewhere else? `creator`

2. In the reverse auction, the sell token is continuously given back as bidders bid to accept less and less of it. Should it be given back to the `creator` or the `beneficiary` or somewhere else? `beneficiary`

3. On auction expiry, if the full lot hasn't been claimed the remainder can be reclaimed from escrow. Should it be returned to the `creator` or the `beneficiary`? `creator`

**Comment by rainbeam** [comment]
@nmushegian any preferences regarding the above?

**Comment by nmushegian** [comment]
1) creator 2) beneficiary

**Comment by rainbeam** [comment]
@nmushegian see new Q3 as well.

**Comment by nmushegian** [comment]
"Full lot hasn't been claimed" meaning there is at least one auctionlet with 0 bids? Unfortunately I can think of use cases for both. For maker's purposes, we want `creator`, so start with that and then let's decide if/how to make the beneficiary an option.

**Comment by rainbeam** [comment]
There are two cases where 'full not hasn't been claimed' can happen:

1. No bids at all.

2. Only split bids made.

Practically, (1) might happen if e.g. the starting bid is set too high; (2) could happen similarly, or if the lot is really big.

**Comment by nmushegian** [comment]
It could also happen if there is a split bid then a normal bid on just the offshoot auctionlet. Point is, I think it makes to formulate the problem as what to do with an auctionlet that has 0 bids (has no real last_bidder).

**Comment by rainbeam** [comment]
Closed by 2b1bff45 and 5fdef3b.
